// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyvlqzrxpwhlrltleuuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dmxxenJ4cHdobHJsdGxldXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDU2NjcsImV4cCI6MjA2NTkyMTY2N30.3kwai-k5hmNRcf_7ZmP8NJs5nKde4L4hBfqbcCRKrPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);